name: Build and Deploy
on: 
  push:
    branches: [master]
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          TRAVIS_TOKEN=${{ secrets.TRAVIS_TOKEN }} npm run fetch
          PUBLIC_URL=/travis-dashboard/ CI=false npm run build
          date > build/timestamp.txt

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true 
